### ISSUE TITLE
"User purchase journey" is empty

### ISSUE THREAD

**Issue by Romanavr** [nystudio107/craft-instantanalytics-ga4#5]
### Question
I have the following setup in the plugin settings
![изображение](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/3519951/9484abc1-4f68-44b7-bdbf-a35bf29c17b5)
Actually, almost the same as it was in the old plugin. 
The problem is that "User purchase journey" is empty  and has no events, at the same moment, I can see my purchases, for example, in the "E-commerce purchases".
Also Ifi'll check "Engagment" -> "Events" I can see my events, just an example from twig:
```
{% if instantAnalytics is defined %}
    {% set beginCheckoutEvent = instantAnalytics.create().BeginCheckoutEvent %}
    {% do beginCheckoutEvent.setCurrency('EUR') %}
    {% do beginCheckoutEvent.setValue(craft.commerce.carts.cart) %}
    {% do instantAnalytics.addEvent(beginCheckoutEvent) %}
{% endif %}
```
![изображение](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/3519951/31f0acae-89d3-4bc7-a9f7-21386aded6a9)
I thought maybe I somehow send the event incorrectly
I thought maybe I'm sending the event incorrectly somehow, so I tried to check the GA4 doc.link from the plugin's documentation, but it doesn't work?
https://nystudio107.com/docs/instant-analytics-ga4/using.html#event-reference
![изображение](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/3519951/bea1a08b-7f44-477e-af87-9bf4912a45b6)
![изображение](https://github.com/nystudio107/craft-instantanalytics-ga4/assets/3519951/2faba004-b29a-4532-8c1a-8b32c1e8c790)

Any help would be greatly appreciated. Maybe someone already experienced this before?

**Comment by bossanova808** [comment]
Are you using the front end Google JS, or just IA?

I have just begun my IA work, but I am using only IA (I don't want the front end JS if I can avoid it) - but I am seeing no 'User' activity at all in the analytics, including nothing in the purchase journey.  I can see `begin_checkout` and `purchase` in events, though.

(note the docs are loading for me over at Google fine using the links in the IA docs).

**Comment by Romanavr** [comment]
@bossanova808 Front JS for regular view page tracking & Backend for E-commerce tracking.
The same situation for me, I see events, but I don't see them in user purchase journey

**Comment by khalwat** [comment]
@Romanavr which link specifically does not work in the documentation? I just clicked on a few of them, and they all seemed to work?

**Comment by Romanavr** [comment]
> @Romanavr which link specifically does not work in the documentation? I just clicked on a few of them, and they all seemed to work?

Nevermind, it's language issue, it doesn't work, for example, with the RU part in the link,` ?hl=ru` (this is how I am automatically redirected from URL in your doc.)
https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events?hl=ru#add_payment_info
But works if `?hl=en`
https://developers.google.com/analytics/devguides/collection/protocol/ga4/reference/events?hl=en#add_payment_info

**Comment by khalwat** [comment]
So is there still an issue to resolve here? Or is it just a case of things being moved around in the GUI in GA4?

**Comment by Romanavr** [comment]
> So is there still an issue to resolve here? Or is it just a case of things being moved around in the GUI in GA4?

I haven't found a solution for main problem yet.
Yes, you can call it a GUI issue, but it's not clear why the user's purchase journey isn't working when it perfectly worked before in previous Analytic.
Don't close it please yet, if I or someone finds a solution it would be helpful to share it here.

**Comment by khalwat** [comment]
I found these docs useful when converting over:

https://support.google.com/analytics/answer/11986666?hl=en#zippy=%2Cin-this-article

https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag

**Comment by bossanova808** [comment]
Not sure those docs really help at the moment, although they are useful generally.  

For me, at least (again, with no front end .js) - I am not seeing _any data at all, other than event data_. 

No user data is coming in at all - and therefore all the acquisition, landing page, device info etc is therefore just totally blank.  I don't really think that's a GA GUI issue, as such, it's an IA (not) reporting issue.  I don't think, as it stands, there is any concept of a user/session in IA that is being reported to GA, right?  It's really all just events so far?  Of course I might be missing something/have done something wrong...but it feels like this is all just currently a bit MIA.  So going back to the previous conversation, I think we do indeed need to look at setting a cookie etc. to get that to work, maybe - I have no real idea how it _should_ be working, though.

To confirm on the data side of things, after a week or so of using IA, I am getting these built in things, _only_ as events: 

- page views (including page titles)
- add/remove from cart (but no indication of what was added/removed)
- view item list (bus seemingly no detail for these, no page title etc)
- purchases, with items and values (well, until the ajax changes we're discussing elsewhere - currently not coming through).

& I have manually added some extra event stuff via PHP:

- view cart (which shows the currency and value, but seemingly not the product data I am sending)
- begin checkout (again am sending product data, but no idea if GA is listening...)
- view item details (manually added because of this issue: #6, but I can't seem to surface the item details I am sending in the GA4 UI anyway)
- search (including the search term & # results - honestly this is about the only thing that feels like it is working reasonably well!)

Other than that, all other GA data across the whole GA UI is entirely empty.  So I think there is some way to go here before IA is doing all that it should...most notably in that user/session side of things. 

The GA4 UI is a frickin nightmare honestly - I simply can't tell if the product data from some of those things is just not getting there, or is simply not surface-able - I meant, is there any point in a view item details event being reported if it doesn't easily show the product in question?

Am currently regretting even trying to move to GA4!
